run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: exported
        disabled: false

  goimports:
    local-prefixes: github.com/mallardduck/dirio

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - unparam

    # Exclude known issues
    - linters:
        - staticcheck
      text: "SA1019:" # Ignore deprecation warnings for now

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true