// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mock/mock_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	metadata "github.com/mallardduck/dirio/internal/persistence/metadata"
	iam "github.com/mallardduck/dirio/sdk/iam"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockRepository) AddUserToGroup(ctx context.Context, groupName string, userUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, groupName, userUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockRepositoryMockRecorder) AddUserToGroup(ctx, groupName, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockRepository)(nil).AddUserToGroup), ctx, groupName, userUID)
}

// AttachPolicyToGroup mocks base method.
func (m *MockRepository) AttachPolicyToGroup(ctx context.Context, groupName, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachPolicyToGroup", ctx, groupName, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachPolicyToGroup indicates an expected call of AttachPolicyToGroup.
func (mr *MockRepositoryMockRecorder) AttachPolicyToGroup(ctx, groupName, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPolicyToGroup", reflect.TypeOf((*MockRepository)(nil).AttachPolicyToGroup), ctx, groupName, policyName)
}

// CreateGroup mocks base method.
func (m *MockRepository) CreateGroup(ctx context.Context, groupName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, groupName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockRepositoryMockRecorder) CreateGroup(ctx, groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockRepository)(nil).CreateGroup), ctx, groupName)
}

// DeleteGroup mocks base method.
func (m *MockRepository) DeleteGroup(ctx context.Context, groupName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, groupName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockRepositoryMockRecorder) DeleteGroup(ctx, groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockRepository)(nil).DeleteGroup), ctx, groupName)
}

// DetachPolicyFromGroup mocks base method.
func (m *MockRepository) DetachPolicyFromGroup(ctx context.Context, groupName, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachPolicyFromGroup", ctx, groupName, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachPolicyFromGroup indicates an expected call of DetachPolicyFromGroup.
func (mr *MockRepositoryMockRecorder) DetachPolicyFromGroup(ctx, groupName, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachPolicyFromGroup", reflect.TypeOf((*MockRepository)(nil).DetachPolicyFromGroup), ctx, groupName, policyName)
}

// GetGroup mocks base method.
func (m *MockRepository) GetGroup(ctx context.Context, groupName string) (*metadata.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, groupName)
	ret0, _ := ret[0].(*metadata.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockRepositoryMockRecorder) GetGroup(ctx, groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockRepository)(nil).GetGroup), ctx, groupName)
}

// GetPolicy mocks base method.
func (m *MockRepository) GetPolicy(ctx context.Context, name string) (*metadata.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, name)
	ret0, _ := ret[0].(*metadata.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockRepositoryMockRecorder) GetPolicy(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockRepository)(nil).GetPolicy), ctx, name)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, userUID uuid.UUID) (*metadata.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userUID)
	ret0, _ := ret[0].(*metadata.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, userUID)
}

// GetUserByAccessKey mocks base method.
func (m *MockRepository) GetUserByAccessKey(ctx context.Context, accessKey string) (*metadata.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAccessKey", ctx, accessKey)
	ret0, _ := ret[0].(*metadata.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAccessKey indicates an expected call of GetUserByAccessKey.
func (mr *MockRepositoryMockRecorder) GetUserByAccessKey(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAccessKey", reflect.TypeOf((*MockRepository)(nil).GetUserByAccessKey), ctx, accessKey)
}

// ListGroupNames mocks base method.
func (m *MockRepository) ListGroupNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupNames indicates an expected call of ListGroupNames.
func (mr *MockRepositoryMockRecorder) ListGroupNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupNames", reflect.TypeOf((*MockRepository)(nil).ListGroupNames), ctx)
}

// RemoveUserFromGroup mocks base method.
func (m *MockRepository) RemoveUserFromGroup(ctx context.Context, groupName string, userUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, groupName, userUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockRepositoryMockRecorder) RemoveUserFromGroup(ctx, groupName, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockRepository)(nil).RemoveUserFromGroup), ctx, groupName, userUID)
}

// SetGroupStatus mocks base method.
func (m *MockRepository) SetGroupStatus(ctx context.Context, groupName string, status iam.GroupStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGroupStatus", ctx, groupName, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGroupStatus indicates an expected call of SetGroupStatus.
func (mr *MockRepositoryMockRecorder) SetGroupStatus(ctx, groupName, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupStatus", reflect.TypeOf((*MockRepository)(nil).SetGroupStatus), ctx, groupName, status)
}
