FROM amazon/aws-cli:2.15.0

# 1. copy needed scripts
COPY lib/test_framework.sh ./lib/
COPY lib/validators.sh ./lib/
COPY scripts/awscli.sh ./

# 2. Set bash as the entrypoint
ENTRYPOINT ["/bin/bash"]