// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mock/mock_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	metadata "github.com/mallardduck/dirio/internal/persistence/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateServiceAccount mocks base method.
func (m *MockRepository) CreateServiceAccount(ctx context.Context, sa *metadata.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", ctx, sa)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockRepositoryMockRecorder) CreateServiceAccount(ctx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockRepository)(nil).CreateServiceAccount), ctx, sa)
}

// DeleteServiceAccount mocks base method.
func (m *MockRepository) DeleteServiceAccount(ctx context.Context, accessKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", ctx, accessKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockRepositoryMockRecorder) DeleteServiceAccount(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockRepository)(nil).DeleteServiceAccount), ctx, accessKey)
}

// GetServiceAccount mocks base method.
func (m *MockRepository) GetServiceAccount(ctx context.Context, accessKey string) (*metadata.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccount", ctx, accessKey)
	ret0, _ := ret[0].(*metadata.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockRepositoryMockRecorder) GetServiceAccount(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockRepository)(nil).GetServiceAccount), ctx, accessKey)
}

// GetServiceAccountByUUID mocks base method.
func (m *MockRepository) GetServiceAccountByUUID(ctx context.Context, saUUID uuid.UUID) (*metadata.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountByUUID", ctx, saUUID)
	ret0, _ := ret[0].(*metadata.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountByUUID indicates an expected call of GetServiceAccountByUUID.
func (mr *MockRepositoryMockRecorder) GetServiceAccountByUUID(ctx, saUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountByUUID", reflect.TypeOf((*MockRepository)(nil).GetServiceAccountByUUID), ctx, saUUID)
}

// GetUserByAccessKey mocks base method.
func (m *MockRepository) GetUserByAccessKey(ctx context.Context, accessKey string) (*metadata.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAccessKey", ctx, accessKey)
	ret0, _ := ret[0].(*metadata.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAccessKey indicates an expected call of GetUserByAccessKey.
func (mr *MockRepositoryMockRecorder) GetUserByAccessKey(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAccessKey", reflect.TypeOf((*MockRepository)(nil).GetUserByAccessKey), ctx, accessKey)
}

// ListServiceAccountKeys mocks base method.
func (m *MockRepository) ListServiceAccountKeys(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccountKeys", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccountKeys indicates an expected call of ListServiceAccountKeys.
func (mr *MockRepositoryMockRecorder) ListServiceAccountKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccountKeys", reflect.TypeOf((*MockRepository)(nil).ListServiceAccountKeys), ctx)
}

// SaveServiceAccount mocks base method.
func (m *MockRepository) SaveServiceAccount(ctx context.Context, sa *metadata.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveServiceAccount", ctx, sa)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveServiceAccount indicates an expected call of SaveServiceAccount.
func (mr *MockRepositoryMockRecorder) SaveServiceAccount(ctx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveServiceAccount", reflect.TypeOf((*MockRepository)(nil).SaveServiceAccount), ctx, sa)
}
