// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mock/mock_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	metadata "github.com/mallardduck/dirio/internal/persistence/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdateUser mocks base method.
func (m *MockRepository) CreateOrUpdateUser(ctx context.Context, user *metadata.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateUser indicates an expected call of CreateOrUpdateUser.
func (mr *MockRepositoryMockRecorder) CreateOrUpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateUser", reflect.TypeOf((*MockRepository)(nil).CreateOrUpdateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockRepository) DeleteUser(ctx context.Context, userUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRepositoryMockRecorder) DeleteUser(ctx, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepository)(nil).DeleteUser), ctx, userUID)
}

// GetGroupNamesForUser mocks base method.
func (m *MockRepository) GetGroupNamesForUser(ctx context.Context, userUID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupNamesForUser", ctx, userUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupNamesForUser indicates an expected call of GetGroupNamesForUser.
func (mr *MockRepositoryMockRecorder) GetGroupNamesForUser(ctx, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupNamesForUser", reflect.TypeOf((*MockRepository)(nil).GetGroupNamesForUser), ctx, userUID)
}

// GetPolicy mocks base method.
func (m *MockRepository) GetPolicy(ctx context.Context, name string) (*metadata.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, name)
	ret0, _ := ret[0].(*metadata.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockRepositoryMockRecorder) GetPolicy(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockRepository)(nil).GetPolicy), ctx, name)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, userUID uuid.UUID) (*metadata.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userUID)
	ret0, _ := ret[0].(*metadata.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, userUID)
}

// GetUserByAccessKey mocks base method.
func (m *MockRepository) GetUserByAccessKey(ctx context.Context, accessKey string) (*metadata.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAccessKey", ctx, accessKey)
	ret0, _ := ret[0].(*metadata.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAccessKey indicates an expected call of GetUserByAccessKey.
func (mr *MockRepositoryMockRecorder) GetUserByAccessKey(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAccessKey", reflect.TypeOf((*MockRepository)(nil).GetUserByAccessKey), ctx, accessKey)
}

// ListUsers mocks base method.
func (m *MockRepository) ListUsers(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockRepositoryMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockRepository)(nil).ListUsers), ctx)
}

// RemoveUserFromGroup mocks base method.
func (m *MockRepository) RemoveUserFromGroup(ctx context.Context, groupName string, userUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, groupName, userUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockRepositoryMockRecorder) RemoveUserFromGroup(ctx, groupName, userUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockRepository)(nil).RemoveUserFromGroup), ctx, groupName, userUID)
}
